
# default
spring:
  # 적용시킬 profile
  profiles:
    active: dev
  # multipart form-data 크기 지정
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

server:
  domain: https://wanted66.r-e.kr
  port: 80
  # Mock Mvc test response
  servlet:
    encoding:
      charset: UTF-8
      force: true

  # HTTP ssl 적용
#  ssl:
#    key-store: "classpath:{key}"
#    key-store-type: PKCS12
#    key-password:

# s3
cloud:
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SCRETKEY}
      image-url: ${AWS_IMAGEURL}


kakao:
  client_id: 5d3f977e28b7baf6825e7f34c62fd79a
  redirect_uri: https://wanted66.r-e.kr:80/callback

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/wanted66?createDatabaseIfNotExist=true
    username: root
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost



---
# prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATASOURCE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}



