name: deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Build
        run: |
          cd project
          chmod +x gradlew
          ./gradlew clean build

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_NICKNAME }}/wanted66:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd deploy_data
            sudo docker stop wanted
            sudo docker rm wanted
            sudo docker rmi ${{ secrets.DOCKER_NICKNAME }}/wanted66:latest
            sudo docker pull ${{ secrets.DOCKER_NICKNAME }}/wanted66:latest
            sudo docker run -d -p ${{ secrets.DOCKER_SERVICE_PORT }} --name wanted --network ${{ secrets.DOCKER_NETWORK }} --env-file=${{ secrets.DEPLOY_DATA }} ${{ secrets.DOCKER_NICKNAME }}/wanted66:latest
